include(
  ":plumber-android",
  ":leakcanary-android",
  ":leakcanary-android-core",
  ":leakcanary-android-instrumentation",
  ":leakcanary-android-process",
  ":leakcanary-android-release",
  ":leakcanary-android-sample",
  ":leakcanary-android-utils",
  ":leakcanary-object-watcher",
  ":leakcanary-object-watcher-android",
  ":leakcanary-object-watcher-android-androidx",
  ":leakcanary-object-watcher-android-support-fragments",
  ":shark",
  ":shark-android",
  ":shark-cli",
  ":shark-graph",
  ":shark-hprof",
  ":shark-hprof-test",
  ":shark-log",
  ":shark-test",
  ":leakcanary-deobfuscation-gradle-plugin"
)

enableFeaturePreview("VERSION_CATALOGS")
