name: Mark stale issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'This issue is not actionable without the required information. Please comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it did not provide enough information to make it actionable.'
          stale-issue-label: stale
          stale-pr-label: stale
          any-of-labels: 'status: needs more info, status: needs heap dump'
